#if !canImport(ObjectiveC)
import XCTest

extension Day1Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Day1Tests = [
        ("test_part1_solution", test_part1_solution),
        ("test_part1_test", test_part1_test),
        ("test_part2_solution", test_part2_solution),
        ("test_part2_test", test_part2_test),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Day1Tests.__allTests__Day1Tests),
    ]
}
#endif
